services:

  stations-backend:
    image: 'sebstiian/zippy_stations'
    environment:
      - POSTGRES_DB_HOST=database
      - POSTGRES_DB_PORT=5432
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=data
    ports:
      - "9000:9000"
    networks:
      - zippy-network
    depends_on:
      - database
  database:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=mypassword
    networks:
      - zippy-network
    ports:
      - "5432:5432"
    volumes:
      - database_pgdata:/var/lib/postgresql/data

networks:
  zippy-network:
    driver: bridge
volumes:
  database_pgdata:
    external: true
    name: database_pgdata
