
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-custom
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=999
  - gid=999
reclaimPolicy: Retain
