apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-dynamic
provisioner: file.csi.azure.com
volumeBindingMode: Immediate  # Bind PVs immediately to PVCs
parameters:
  storageAccount: software3zippydatabase
  shareName: database-zippy
  skuName: Standard_RAGRS
  secretName: azure-secret
  resourceGroup: microk8s-cluster-rg
mountOptions:
  - dir_mode=0700
  - file_mode=0700
  - uid=999
  - gid=999
reclaimPolicy: Delete

