apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-read-only-script
data:
  set-read-only.sh: |
    #!/bin/sh
    if [ "$(hostname)" = "database-stateful-0" ]; then
        echo "Primary node detected. Enabling write access."
        psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "ALTER SYSTEM SET default_transaction_read_only TO off;"
        psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT pg_reload_conf();"
    else
        echo "Replica node detected. Enabling read-only mode."
        psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "ALTER SYSTEM SET default_transaction_read_only TO on;"
        psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT pg_reload_conf();"
    fi
