apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-stateful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-stateful
  template:
    metadata:
      labels:
        app: database-stateful
    spec:
      securityContext:
        fsGroup: 999   # Matches the PostgreSQL GID
        runAsUser: 999 # Matches the PostgreSQL UID
      containers:
        - name: database-stateful
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: test
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: data
          ports:
            - containerPort: 5432      
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: nfs-storage-class
        resources:
          requests:
            storage: 5Gi
